### ISSUE TITLE
Implementation about gpt-2-pytorch here

### ISSUE THREAD

**Issue by graykode** [openai/gpt-2#47] opened 2019-02-18 08:51 UTC
https://github.com/graykode/gpt-2-Pytorch

This is my code about Implementation of gpt-2-pytorch
But in first Commit about BackBone Code, This is not running because model can not load *.ckpt file in Pytorch. Also, I wait license on original gpt-2 repository !!
I hope it's good for pythorch developers.

PS) Thanks for @WuTheFWasThat  for allowing

**Comment by WuTheFWasThat** [comment] 2019-02-19 00:27
regarding loading checkpoint file, that seems like a pytorch question
duplicate of https://github.com/openai/gpt-2/issues/10

**Closed by WuTheFWasThat** 2019-02-19 00:27 UTC
